apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      dev: {{ .Values.name }}
  template:
    metadata:
      labels:
        dev: {{ .Values.name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          #livenessProbe:
            #httpGet:
              #path: /api/graphql
              #port: 8050
            #initialDelaySeconds: 0
            #timeoutSeconds: 1
            #periodSeconds: 15
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

